# -*- coding: utf-8 -*-
"""Data analytics(VaR).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dwB_gDU0QW51SpvSq80hvKE6Lcis6qUY
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd               #handling data
import numpy as np                #calculations.
import matplotlib.pyplot as plt   #plotting
import seaborn as sns             #data visulaization
from pandas_datareader import data as pdr   #backup data source (Stooq).
import yfinance as yf           #main data source (Yahoo Finance).
import datetime as dt           #set start/end dates
from scipy import stats         #used for statistical tests
import time                     #to pause between downloads (avoid rate limits).

sns.set_style('whitegrid')
# %matplotlib inline

tickers = ['NVDA','AAPL','GOOGL','AMZN']
weights = np.array([0.25,0.25,0.25,0.25])

start = dt.datetime(2021,1,1)
end = dt.datetime.today()

#Creates a calendar of dates from start to end
# prices = pd.DataFrame(index=pd.date_range(start,end)) #this was givng empty frame bcz of index mismatching
prices = pd.DataFrame()

for ticker in tickers:
  print(f"Fetching {ticker}...", end=" ")
  try:
    #pull via yfinance.Ticker.history (auto_adjust -> splits/divs handled)
    df = yf.Ticker(ticker).history(
        start=start.strftime('%Y-%m-%d'),
        end=end.strftime('%Y-%m-%d'),
        auto_adjust=True
    )
    series = df['Close']
    print("Done yfinance", end="")
  except Exception as e:
    #Fallback to Stooq if yfinance fails
    print(f"X yfinance ({e}); falling back to stooq", end="")
    df2 = pdr.DataReader(ticker,'stooq',start,end)
    df2 = df2.sort_index()
    series = df2['Close']
  #align on our master date index
  prices[ticker] = series
  time.sleep(1) #pause to respect rate limit
  print()

  #ffill = forward(above values will get fill in blanked)fill
#bfill = backward(below values will get fill in blanked)fill
prices = prices.dropna(how='all').ffill().bfill() #remove any row where all columns are NaN


#quick sanity check/Shows last few rows of prices for a quick check.
print(f"\n'Daily prices(tails)'\n {prices.tail()}")

# Daily log returns
log_returns = np.log(prices / prices.shift(1))

# Remove the first NaN row
log_returns = log_returns.dropna()

# Quick check
print(f"\n'Daily log returns(Tails)'\n{log_returns.tail()}")

from scipy.stats import norm
plt.figure(figsize=(12, 6))

# Histogram with density curve
sns.histplot(log_returns['NVDA'], bins=50, stat='density', alpha=0.7, label='Actual Returns')

# Overlay normal distribution
mu, sigma = log_returns['NVDA'].mean(), log_returns['NVDA'].std()
x = np.linspace(-0.15, 0.15, 100)
plt.plot(x, norm.pdf(x, mu, sigma), 'r--', label='Normal Curve')

# Highlight extremes
plt.axvspan(0.03, 0.15, color='green', alpha=0.2, label='Big Gains (>3%)')
plt.axvspan(-0.15, -0.03, color='red', alpha=0.2, label='Big Losses (<-3%)')

plt.title('NVDA: Positive Skew = More Frequent Big Gains (But Losses Still Exist)')
plt.xlabel('Daily Log Returns')
plt.legend()
plt.show()

# Calculate descriptive statistics
summary_stats = pd.DataFrame({
    'log_returns Mean': log_returns.mean(),
    'log_returns Variance': log_returns.var(),
    'log_returns Skewness': log_returns.skew(),
    'log_returns Kurtosis': log_returns.kurtosis()
})
pd.set_option("display.width", 200)
pd.set_option("display.max_columns", None)
print(summary_stats)




print("\nCONCLUSION : \nAccording to Skewness : NVDA and AAPL are positively skewed → More frequent large gains. \n                        GOOGL and AMZN are negatively skewed → More frequent large losses.\nAccording to Kurtosis : AAPL and AMZN are most prone to surprise extreme moves (good or bad).")
print("\nRESULTS : \nMore big gains: NVDA (+22% skew), AAPL (+25% skew).\n"
"More big losses: GOOGL (-14% skew), AMZN (-14% skew).")

# Calculate the average daily log return for each stock
avg_daily_log_returns = log_returns.mean()

print("Average Daily Log Returns for Each Stock:")
print(avg_daily_log_returns)

# Calculate daily variance for each stock
daily_variance = log_returns.var()


# Rank from most to least volatile
print("\n📈 Ranked by Volatility/Variance (Most Bumpy to Least):")
print(daily_variance.sort_values(ascending=False))

# Calculate daily standard deviation for each stock
daily_std = log_returns.std()

# Rank from most to least volatile
print("\n📈 Ranked by Standard Deviation (Most Bumpy to Least):")
print(daily_std.sort_values(ascending=False))

# Show both together for comparison
print("\n=== COMBINED VIEW ===")
risk_metrics = pd.DataFrame({
    'Variance': daily_variance,
    'Std_Dev': daily_std,
    'Std_Dev_Pct': daily_std * 100  # Convert to percentage
})

print(risk_metrics.sort_values('Std_Dev', ascending=False))

# Create DataFrame with all statistics
stock_stats = pd.DataFrame({
    'Mean': log_returns.mean(),
    'Variance': log_returns.var(),
    'Std_Dev': log_returns.std(),
    'Skewness': log_returns.skew(),
    'Kurtosis': log_returns.kurtosis()
})

# Print the complete statistics DataFrame
print("=== COMPLETE STATISTICS FOR ALL STOCKS ===")
print(stock_stats)

# This calculates for EACH stock separately
print("=== ANALYSIS FOR EACH INDIVIDUAL STOCK ===")

# Mean (μ) for each stock
stock_means = log_returns.mean()
print("\nAverage Daily Return (μ) for each stock:")
print(stock_means)

# Standard Deviation (σ) for each stock
stock_std = log_returns.std()
print("\nDaily Standard Deviation (σ) for each stock:")
print(stock_std)

# Interpretation for each stock
for stock in log_returns.columns:
    mu = stock_means[stock]
    sigma = stock_std[stock]

    trend = "gains more common" if mu > 0 else "losses more common"
    volatility = "stable" if sigma < 0.02 else "volatile" if sigma > 0.03 else "moderate"

    print(f"\n{stock}: μ = {mu:.4f} ({trend}), σ = {sigma:.4f} ({volatility})")

print("=== FITTING NORMAL DISTRIBUTION & 95% CONFIDENCE INTERVAL FOR MEAN & std (z-score & chi-sq) - INDIVIDUAL STOCKS ===")
print("="*65)

# Calculate for each stock
confidence_intervals = {}

for stock in log_returns.columns:
    returns = log_returns[stock]
    mu = returns.mean()

    n = len(returns)

    # Calculate 95% CI for mean
    ci_low, ci_high = stats.norm.interval(0.95, loc=mu, scale=sigma/np.sqrt(n))
    confidence_intervals[stock] = (ci_low, ci_high)



# Create a nice DataFrame for display
ci_df = pd.DataFrame(confidence_intervals, index=['CI_Lower', 'CI_Upper']).T
ci_df['Mean'] = log_returns.mean()

ci_df = ci_df[['Mean', 'CI_Lower', 'CI_Upper']]

print("\n📊 Summary Table:")
print(ci_df)

# First, create the portfolio returns
portfolio_returns = log_returns.mean(axis=1)  # Equal-weighted portfolio


print("=== 95% CONFIDENCE INTERVAL FOR MEAN USING Z-SCORE ===")
print("Formula: Mean ± (Z * σ/√n)")
print("="*55)

# Calculate components
mu = portfolio_returns.mean()
sigma = portfolio_returns.std()
n = len(portfolio_returns)
std_error = sigma / np.sqrt(n)
z_score = 1.96  # For 95% confidence

# Calculate margin of error and CI
margin_of_error = z_score * std_error
ci_lower = mu - margin_of_error
ci_upper = mu + margin_of_error

print(f"Mean (μ): {mu:.6f}")
print(f"Std Dev (σ): {sigma:.6f}")
print(f"Sample Size (n): {n}")
print(f"Standard Error (σ/√n): {std_error:.6f}")
print(f"Z-score (95%): {z_score}")
print(f"Margin of Error: {margin_of_error:.6f}")
print(f"\n95% CI: [{ci_lower:.6f}, {ci_upper:.6f}]")

print("=== 95% CI FOR STANDARD DEVIATION (CHI-SQUARE METHOD) ===")
print("-"*60)

# Your portfolio parameters
sigma = portfolio_returns.std()  # Sample standard deviation
n = len(portfolio_returns)       # Sample size
df = n - 1                       # Degrees of freedom

print(f"Sample Std Dev (σ): {sigma:.6f}")
print(f"Sample Size (n): {n}")


# Get chi-square critical values
chi2_lower = stats.chi2.ppf(0.975, df)  # 97.5th percentile
chi2_upper = stats.chi2.ppf(0.025, df)  # 2.5th percentile

print(f"\nChi-square critical values:")
print(f"χ²(0.975, {df}) = {chi2_lower:.2f}")
print(f"χ²(0.025, {df}) = {chi2_upper:.2f}")

# Calculate confidence interval for standard deviation
ci_std_lower = sigma * np.sqrt((n-1) / chi2_lower)
ci_std_upper = sigma * np.sqrt((n-1) / chi2_upper)


print(f"Final 95% CI: [{ci_std_lower:.6f}, {ci_std_upper:.6f}]")

# Fit t-distribution
df, mu_t, sigma_t = stats.t.fit(portfolio_returns)

print(f"t-distribution parameters:")
print(f"Location (μ): {mu_t:.6f}       (the avg daily return 'centere of the curve')")
print(f"Scale (σ): {sigma_t:.6f}       (the spread of returns'both gain and losses)")
print(f"Degrees of freedom: {df:.2f}   (how fat the tails of curve are ,fewer degree of freedom =more chances of extreme events and more hte df is more it is likly to be normal dist)")

print("=== Estimating Confidence Intervals Using Bootstrapping ===")
print("="*60)
print("Bootstrap + t-distribution method (hybrid approach)")
print("="*60)



# Set parameters
n_bootstrap = 10000  # Number of bootstrap samples
confidence_level = 0.95
alpha = (1 - confidence_level)

# Initialize arrays to store bootstrap results
bootstrap_means = np.zeros(n_bootstrap)
bootstrap_stds = np.zeros(n_bootstrap)
bootstrap_t_cis = np.zeros((n_bootstrap, 2))  # Store CI for each bootstrap sample

# Get original sample statistics
n_original = len(portfolio_returns)
original_mean = portfolio_returns.mean()
original_std = portfolio_returns.std()

# Perform bootstrapping with t-distribution
for i in range(n_bootstrap):
    # Resample with replacement
    bootstrap_sample = portfolio_returns.sample(n=n_original, replace=True)

    # Calculate sample statistics
    sample_mean = bootstrap_sample.mean()
    sample_std = bootstrap_sample.std()
    sample_size = len(bootstrap_sample)

    # Store basic statistics
    bootstrap_means[i] = sample_mean
    bootstrap_stds[i] = sample_std

    # Calculate t-distribution CI for this bootstrap sample
    t_critical = stats.t.ppf(1 - alpha/2, df=sample_size-1)
    se = sample_std / np.sqrt(sample_size)

    lower_ci = sample_mean - t_critical * se
    upper_ci = sample_mean + t_critical * se

    bootstrap_t_cis[i] = [lower_ci, upper_ci]

# Calculate overall confidence intervals
# Method 1: Percentile method on means (standard bootstrap)
ci_mean_percentile = np.percentile(bootstrap_means, [2.5, 97.5])

# Method 2: Average of all t-distribution CIs
avg_t_lower = np.mean(bootstrap_t_cis[:, 0])
avg_t_upper = np.mean(bootstrap_t_cis[:, 1])

# Method 3: Percentile of t-distribution CIs
ci_t_lower_percentile = np.percentile(bootstrap_t_cis[:, 0], 2.5)
ci_t_upper_percentile = np.percentile(bootstrap_t_cis[:, 1], 97.5)

# ========== ADDED: Calculate CI for Standard Deviation (σ) ==========
ci_std_percentile = np.percentile(bootstrap_stds, [2.5, 97.5])
# ===================================================================

print(f"Number of bootstrap samples: {n_bootstrap}")
print(f"Confidence level: {confidence_level*100}%")
print(f"Original sample size: {n_original}")
print(f"Original mean: {original_mean:.6f}")
print(f"Original standard deviation: {original_std:.6f}")

print(f"\n📊 Standard Bootstrap 95% CI for Mean (μ):")
print(f"[{ci_mean_percentile[0]:.6f}, {ci_mean_percentile[1]:.6f}]")
print("We are 95% sure the true average return falls between these two numbers")

print(f"\n📊 Standard Bootstrap 95% CI for Standard Deviation (σ):")
print(f"[{ci_std_percentile[0]:.6f}, {ci_std_percentile[1]:.6f}]")
print("We are 95% sure the true risk level falls between these two numbers")

print(f"\n📊 Bootstrap + t-distribution 95% CI for Mean (Average of t-CIs):")
print(f"[{avg_t_lower:.6f}, {avg_t_upper:.6f}]")

print(f"\n📊 Bootstrap + t-distribution 95% CI for Mean (Percentile of t-CIs):")
print(f"[{ci_t_lower_percentile:.6f}, {ci_t_upper_percentile:.6f}]")

# Compare with traditional t-distribution CI (without bootstrap)
t_critical_original = stats.t.ppf(1 - alpha/2, df=n_original-1)
se_original = original_std / np.sqrt(n_original)
traditional_t_ci = [
    original_mean - t_critical_original * se_original,
    original_mean + t_critical_original * se_original
]

print(f"\n📊 Traditional t-distribution 95% CI (without bootstrap):")
print(f"[{traditional_t_ci[0]:.6f}, {traditional_t_ci[1]:.6f}]")

# Additional analysis: Check coverage of original mean
coverage_count = np.sum((bootstrap_t_cis[:, 0] <= original_mean) &
                       (bootstrap_t_cis[:, 1] >= original_mean))
coverage_percentage = (coverage_count / n_bootstrap) * 100

print(f"\n📈 Coverage analysis: {coverage_percentage:.1f}% of bootstrap t-CIs contain the original mean")

print("=== Estimating Portfolio Risk and Value at Risk (VaR) Using a Normal Distribution ===")
print("="*40)

# Step 1: Calculate portfolio return statistics
# Assuming portfolio_returns is your daily returns series
daily_mean = portfolio_returns.mean()
daily_std = portfolio_returns.std()
n_days = len(portfolio_returns)

print(f"Portfolio Analysis ({n_days} trading days)")
print(f"Daily Mean Return: {daily_mean:.6f} ({daily_mean*100:.4f}%)")
print(f"Daily Standard Deviation: {daily_std:.6f} ({daily_std*100:.4f}%)")

# Annualize returns (assuming 252 trading days)
annual_mean = daily_mean * 252
annual_std = daily_std * np.sqrt(252)

print(f"\nAnnualized Statistics:")
print(f"Annual Mean Return: {annual_mean:.6f} ({annual_mean*100:.2f}%)")
print(f"Annual Volatility: {annual_std:.6f} ({annual_std*100:.2f}%)")

# Step 2: Estimate worst-case scenario with 95% CI
confidence_level = 0.95
alpha = 1 - confidence_level

# Calculate z-score for 95% confidence
z_score = stats.norm.ppf(1 - alpha/2)

# Confidence interval for mean return
se_mean = daily_std / np.sqrt(n_days)
ci_lower_mean = daily_mean - z_score * se_mean
ci_upper_mean = daily_mean + z_score * se_mean

# Value at Risk (VaR) calculation
var_95 = daily_mean - stats.norm.ppf(0.95) * daily_std
expected_shortfall = daily_mean - (daily_std * stats.norm.pdf(stats.norm.ppf(0.95)) / 0.05)

print(f"\n📉 RISK ASSESSMENT (95% Confidence):")
print(f"95% CI for Mean Return: [{ci_lower_mean:.6f}, {ci_upper_mean:.6f}]")
print(f"95% CI for Mean Return: [{ci_lower_mean*100:.4f}%, {ci_upper_mean*100:.4f}%]")
print(f"Daily Value at Risk (VaR 95%): {var_95:.6f} ({var_95*100:.4f}%)")
print(f"Expected Shortfall (CVaR 95%): {expected_shortfall:.6f} ({expected_shortfall*100:.4f}%)")

# Worst-case scenarios at different confidence levels
print(f"\n🔍 WORST-CASE SCENARIOS:")
print(f"{'Confidence':<12} {'Daily Loss':<15} {'Annual Loss':<15}")
print("-" * 45)

confidence_levels = [0.90, 0.95, 0.99]
for cl in confidence_levels:
    daily_loss = daily_mean - stats.norm.ppf(cl) * daily_std
    annual_loss = annual_mean - stats.norm.ppf(cl) * annual_std
    print(f"{cl*100:.0f}%{'':<8} {daily_loss*100:>8.2f}%{'':<6} {annual_loss*100:>8.2f}%")

# Step 3: Interpretation
print(f"\n💡 INTERPRETATION:")
print(f"1. With 95% confidence, the true average daily return is between {ci_lower_mean*100:.4f}% and {ci_upper_mean*100:.4f}%")
print(f"2. There's a 5% chance of losing more than {abs(var_95)*100:.2f}% in a single day")
print(f"3. If a bad day occurs (worst 5%), the average loss would be {abs(expected_shortfall)*100:.2f}%")
print(f"4. Annual volatility of {annual_std*100:.2f}% indicates the portfolio's risk level")
print(f"5. Sharpe Ratio (assuming 0 risk-free): {annual_mean/annual_std:.2f}")

print("=== VALUE AT RISK (VaR) USING STUDENT'S T-DISTRIBUTION ===")
print("="*55)


print(f"✅ Using existing t-distribution parameters:")
print(f"   Degrees of freedom (df): {df:.4f}")
print(f"   Location parameter (μ): {mu:.6f} ({mu*100:.4f}%)")
print(f"   Scale parameter (σ): {sigma:.6f} ({sigma*100:.4f}%)")

# Step 2: Identify the 5% cutoff for a "worst-case day"
confidence_level = 0.95
alpha = 1 - confidence_level
t_critical = stats.t.ppf(alpha, df=df)  # 5% left tail critical value

print(f"\n✅ Step 2: Found 5% cutoff (t-critical value)")
print(f"   Confidence level: {confidence_level*100}%")
print(f"   t₀.₀₅ (critical value): {t_critical:.6f}")

# Step 3: Calculate the 1-day VaR using the formula
var_t = -(mu + sigma * t_critical)

print(f"\n✅ Step 3: Calculated VaR using Student's t-distribution")
print(f"   VaR Formula: – (μ + σ × t₀.₀₅)")
print(f"   VaR = – ({mu:.6f} + {sigma:.6f} × {t_critical:.6f})")
print(f"   VaR = {var_t:.6f} ({var_t*100:.4f}%)")

# Compare with normal distribution VaR for reference
var_normal = -(mu + sigma * stats.norm.ppf(alpha))

print(f"\n📊 COMPARISON WITH NORMAL DISTRIBUTION:")
print(f"   Normal Distribution VaR (95%): {var_normal*100:.4f}%")
print(f"   t-Distribution VaR (95%): {var_t*100:.4f}%")
print(f"   Difference: {(var_t - var_normal)*100:.4f}%")

# Step 4: Interpret the result
print(f"\n✅ Step 4: Interpretation of Results")
print(f"💡 KEY INSIGHTS:")
print(f"1. FAT TAILS: Degrees of freedom = {df:.2f}")
if df < 30:
    print(f"   → Low df indicates fatter tails than normal distribution")
    print(f"   → Higher probability of extreme losses")
else:
    print(f"   → Similar to normal distribution tails")

print(f"2. DAILY RISK: With 95% confidence, don't lose more than {abs(var_t)*100:.2f}% in a day")
print(f"3. TAIL RISK: t-distribution VaR is {abs(var_t - var_normal)*100:.2f}% higher than normal")
print(f"   → Normal distribution underestimates tail risk")

# Additional risk metrics at different confidence levels
print(f"\n📈 VaR AT DIFFERENT CONFIDENCE LEVELS:")
print(f"{'Confidence':<12} {'t-VaR':<15} {'Normal VaR':<15} {'Difference':<15}")
print("-" * 60)

confidence_levels = [0.90, 0.95, 0.99]
for cl in confidence_levels:
    alpha_cl = 1 - cl
    t_var = -(mu + sigma * stats.t.ppf(alpha_cl, df=df))
    normal_var = -(mu + sigma * stats.norm.ppf(alpha_cl))
    diff = t_var - normal_var

    print(f"{cl*100:.0f}%{'':<8} {t_var*100:>8.2f}%{'':<6} {normal_var*100:>8.2f}%{'':<6} {diff*100:>8.2f}%")

# Calculate Expected Shortfall (CVaR) for t-distribution
print(f"\n📊 EXPECTED SHORTFALL (Conditional VaR):")
cvar_t = -stats.t.expect(lambda x: x, args=(df,), loc=mu, scale=sigma,
                        lb=stats.t.ppf(alpha, df=df), ub=np.inf)
print(f"   t-Distribution CVaR (95%): {cvar_t*100:.4f}%")

print("=== Estimating Value at Risk (VaR) Using Historical Returns ===")
print("="*45)

# Step 1: Arrange portfolio's daily returns from worst to best
sorted_returns = np.sort(returns)
print(f"✅ Step 1: Sorted {len(returns)} daily returns from worst to best")
print(f"   Worst return: {sorted_returns[0]*100:.2f}%")
print(f"   Best return: {sorted_returns[-1]*100:.2f}%")

# Step 2: Find the 5th percentile return (for 95% VaR)
confidence_level = 0.95
percentile = (1 - confidence_level) * 100  # 5th percentile
var_index = int((1 - confidence_level) * len(sorted_returns))
percentile_return = sorted_returns[var_index]

print(f"\n✅ Step 2: Found {percentile}th percentile return")
print(f"   Index position: {var_index} (out of {len(returns)} returns)")
print(f"   {percentile}th percentile return: {percentile_return:.6f} ({percentile_return*100:.4f}%)")

# Step 3: Express as positive Value at Risk
var_95 = abs(percentile_return)

print(f"\n✅ Step 3: Expressed as positive Value at Risk")
print(f"   VaR ({confidence_level*100}%) = |{percentile_return:.6f}| = {var_95:.6f}")
print(f"   Historical VaR (95%): {var_95*100:.4f}%")

# Show the exact VaR cutoff point
print(f"\n📊 VaR CUTOFF DETAILS:")
print(f"   Return at position {var_index-1}: {sorted_returns[var_index-1]*100:.4f}%")
print(f"   Return at position {var_index}: {sorted_returns[var_index]*100:.4f}% ← 95% VaR CUTOFF")
print(f"   Return at position {var_index+1}: {sorted_returns[var_index+1]*100:.4f}%")

# Count how many returns are worse than the VaR cutoff
returns_worse_than_var = sorted_returns[sorted_returns < percentile_return]
print(f"   Number of returns worse than VaR: {len(returns_worse_than_var)}")
print(f"   Expected number: {int((1-confidence_level)*len(sorted_returns))}")

# Interpretation
print(f"\n💡 INTERPRETATION:")
print(f"   Based on {len(returns)} days of historical data:")
print(f"   • There's a 5% chance of losing {var_95*100:.2f}% or more in a day")
print(f"   • On 95% of days, losses won't exceed {var_95*100:.2f}%")
print(f"   • {len(returns_worse_than_var)} actual days were worse than this VaR level")

# Practical example
portfolio_value = 1000000  # $1,000,000 portfolio
print(f"\n💰 PRACTICAL EXAMPLE (${portfolio_value:,.0f} portfolio):")
print(f"   Daily VaR (95%): ${portfolio_value * var_95:,.0f}")
print(f"   'We're 95% confident we won't lose more than ${portfolio_value * var_95:,.0f} in a day'")

print("=== TESTING PORTFOLIO RETURN STATISTICAL SIGNIFICANCE ===")
print("="*60)

print(f"📊 PORTFOLIO PARAMETERS:")
print(f"   Daily mean return (μ): {mu:.6f} ({mu*100:.4f}%)")
print(f"   Daily volatility (σ): {sigma:.6f} ({sigma*100:.4f}%)")
print(f"   Number of observations (n): {n} trading days")
print(f"   Annualized return: {mu*252*100:.2f}%")
print(f"   Annualized volatility: {sigma*np.sqrt(252)*100:.2f}%")

# Step 1: One-sample t-test (test if mean return ≠ 0)
print(f"\n✅ STEP 1: ONE-SAMPLE T-TEST")
print(f"   Null Hypothesis (H₀): True mean return = 0%")
print(f"   Alternative Hypothesis (H₁): True mean return ≠ 0%")

# Calculate t-statistic and p-value
t_statistic = (mu - 0) / (sigma / np.sqrt(n))
p_value = 2 * (1 - stats.t.cdf(abs(t_statistic), df=n-1))

print(f"   t-statistic: {t_statistic:.4f}")
print(f"   p-value: {p_value:.6f}")

# Interpretation
alpha = 0.05  # 95% confidence level
if p_value < alpha:
    print(f"   ✅ STATISTICALLY SIGNIFICANT: p-value ({p_value:.4f}) < α ({alpha})")
    print(f"   → Reject null hypothesis → Mean return is significantly different from 0")
else:
    print(f"   ❌ NOT STATISTICALLY SIGNIFICANT: p-value ({p_value:.4f}) > α ({alpha})")
    print(f"   → Fail to reject null hypothesis → Mean return not significantly different from 0")

# Step 2: Calculate confidence interval for mean return
print(f"\n✅ STEP 2: CONFIDENCE INTERVAL FOR MEAN RETURN")
t_critical = stats.t.ppf(1 - alpha/2, df=n-1)
se = sigma / np.sqrt(n)  # Standard error
ci_lower = mu - t_critical * se
ci_upper = mu + t_critical * se

print(f"   Standard Error: {se:.6f}")
print(f"   t-critical value (95%): ±{t_critical:.4f}")
print(f"   95% Confidence Interval: [{ci_lower:.6f}, {ci_upper:.6f}]")
print(f"   95% Confidence Interval: [{ci_lower*100:.4f}%, {ci_upper*100:.4f}%]")

# Check if 0 is within the confidence interval
if ci_lower > 0 or ci_upper < 0:
    print(f"   ✅ 0 is NOT in the confidence interval → Significant")
else:
    print(f"   ❌ 0 is in the confidence interval → Not Significant")

# Step 3: Calculate the minimum significant return
print(f"\n✅ STEP 3: MINIMUM SIGNIFICANT RETURN")
min_significant_return = t_critical * se
print(f"   Minimum return needed for significance: {min_significant_return:.6f} ({min_significant_return*100:.4f}%)")
print(f"   Your actual return: {mu:.6f} ({mu*100:.4f}%)")

if abs(mu) > min_significant_return:
    print(f"   ✅ Your return exceeds minimum for significance")
else:
    print(f"   ❌ Your return below minimum for significance")

# Step 4: Power analysis
print(f"\n✅ STEP 4: POWER ANALYSIS")
# What effect size could we detect with 80% power?
from statsmodels.stats.power import TTestPower
power_analysis = TTestPower()
effect_size = power_analysis.solve_power(effect_size=None, power=0.8, nobs=n, alpha=alpha)

# Convert effect_size to scalar if it's an array
if hasattr(effect_size, 'item'):  # Check if it's a numpy array
    effect_size_scalar = effect_size.item()
else:
    effect_size_scalar = float(effect_size)

min_detectable_effect = effect_size_scalar * sigma

print(f"   With {n} observations and 80% power, we can detect:")
print(f"   Minimum detectable effect size: {effect_size_scalar:.4f} standard deviations")
print(f"   Minimum detectable return: {min_detectable_effect:.6f} ({min_detectable_effect*100:.4f}%)")

# Step 5: Compare to benchmark (risk-free rate)
print(f"\n✅ STEP 5: COMPARISON TO BENCHMARK")
# Assuming risk-free rate ≈ 0 for daily returns (or use actual risk-free rate)
risk_free_rate = 0.0000  # Approximately 0% daily
excess_return = mu - risk_free_rate
sharpe_ratio = excess_return / sigma * np.sqrt(252)  # Annualized Sharpe ratio

print(f"   Risk-free rate (daily): {risk_free_rate*100:.4f}%")
print(f"   Excess return (daily): {excess_return*100:.4f}%")
print(f"   Annualized Sharpe ratio: {sharpe_ratio:.4f}")

# Test if Sharpe ratio is significant
# Using standard error of Sharpe ratio ≈ 1/sqrt(n)
sharpe_se = 1 / np.sqrt(n)
sharpe_z = sharpe_ratio / sharpe_se
sharpe_p_value = 2 * (1 - stats.norm.cdf(abs(sharpe_z)))

print(f"   Sharpe ratio standard error: {sharpe_se:.4f}")
print(f"   Sharpe ratio z-score: {sharpe_z:.4f}")
print(f"   Sharpe ratio p-value: {sharpe_p_value:.6f}")

if sharpe_p_value < alpha:
    print(f"   ✅ Sharpe ratio is statistically significant")
else:
    print(f"   ❌ Sharpe ratio is not statistically significant")

# Visualization
plt.figure(figsize=(15, 10))

# Plot 1: Distribution of returns with hypothesis test
plt.subplot(2, 2, 1)
x = np.linspace(mu - 4*se, mu + 4*se, 100)
plt.plot(x, stats.t.pdf(x, df=n-1, loc=mu, scale=se), 'b-', label='Sampling Distribution')
plt.axvline(mu, color='green', linestyle='-', label=f'Sample Mean: {mu*100:.4f}%')
plt.axvline(0, color='red', linestyle='--', label='Null Hypothesis (μ=0)')

# Shade the rejection regions
x_reject_left = np.linspace(mu - 4*se, -t_critical * se, 100)
x_reject_right = np.linspace(t_critical * se, mu + 4*se, 100)
plt.fill_between(x_reject_left, stats.t.pdf(x_reject_left, df=n-1, loc=mu, scale=se),
                 alpha=0.3, color='red', label='Rejection Region')
plt.fill_between(x_reject_right, stats.t.pdf(x_reject_right, df=n-1, loc=mu, scale=se),
                 alpha=0.3, color='red')

plt.title('Hypothesis Test: Is Mean Return Significantly Different from 0?')
plt.xlabel('Mean Return')
plt.ylabel('Probability Density')
plt.legend()
plt.grid(True, alpha=0.3)

# Plot 2: Confidence interval
plt.subplot(2, 2, 2)
plt.errorbar(0, mu, yerr=t_critical*se, fmt='o', capsize=10,
            label=f'95% CI: [{ci_lower*100:.4f}%, {ci_upper*100:.4f}%]')
plt.axhline(0, color='red', linestyle='--', label='Null Hypothesis (μ=0)')
plt.axhline(mu, color='green', linestyle='-', label=f'Sample Mean: {mu*100:.4f}%')

plt.xlim(-0.5, 0.5)
plt.title('Confidence Interval for Mean Return')
plt.ylabel('Daily Return')
plt.xticks([])
plt.legend()
plt.grid(True, alpha=0.3)

# Plot 3: p-value interpretation
plt.subplot(2, 2, 3)
p_values = np.linspace(0.001, 0.1, 100)
plt.axvline(alpha, color='red', linestyle='--', label=f'α = {alpha}')
plt.axvline(p_value, color='blue', linestyle='-', label=f'p-value = {p_value:.4f}')
plt.fill_betweenx([0, 1], 0, alpha, alpha=0.3, color='green', label='Significant Region')
plt.fill_betweenx([0, 1], alpha, 0.1, alpha=0.3, color='orange', label='Not Significant')

plt.title('p-value Interpretation')
plt.xlabel('p-value')
plt.ylabel('')
plt.yticks([])
plt.legend()
plt.grid(True, alpha=0.3)

# Plot 4: Sharpe ratio distribution
plt.subplot(2, 2, 4)
x_sharpe = np.linspace(-1, 3, 100)
plt.plot(x_sharpe, stats.norm.pdf(x_sharpe, loc=sharpe_ratio, scale=sharpe_se), 'b-')
plt.axvline(sharpe_ratio, color='green', linestyle='-', label=f'Sample Sharpe: {sharpe_ratio:.3f}')
plt.axvline(0, color='red', linestyle='--', label='Null (Sharpe=0)')

# Shade extreme regions
x_extreme = np.linspace(2*sharpe_se, 3, 100)
plt.fill_between(x_extreme, stats.norm.pdf(x_extreme, loc=sharpe_ratio, scale=sharpe_se),
                 alpha=0.3, color='red', label='Extreme Values')

plt.title('Sharpe Ratio Distribution')
plt.xlabel('Sharpe Ratio')
plt.ylabel('Density')
plt.legend()
plt.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

print(f"\n🎯 FINAL CONCLUSION:")
if p_value < alpha:
    print(f"✅ YOUR PORTFOLIO RETURN IS STATISTICALLY SIGNIFICANT!")
    print(f"   • The positive return is unlikely due to random chance")
    print(f"   • You can be 95% confident the true mean return is positive")
    print(f"   • This suggests genuine investment skill or strategy edge")
else:
    print(f"❌ YOUR PORTFOLIO RETURN IS NOT STATISTICALLY SIGNIFICANT")
    print(f"   • The observed return could be due to random chance")
    print(f"   • You cannot rule out that the true mean return is zero or negative")
    print(f"   • Consider: more data, higher returns, or lower volatility")

print(f"\n📈 RECOMMENDATIONS:")
print(f"1. Sample size: {n} observations {'is good' if n > 250 else 'could be larger'}")
print(f"2. Effect size: {mu/sigma:.4f} sigma {'is strong' if mu/sigma > 0.1 else 'is weak'}")
print(f"3. Confidence: 95% CI suggests true return between {ci_lower*100:.4f}% and {ci_upper*100:.4f}%")

print("=== PORTFOLIO DIVERSIFICATION ANALYSIS ===")
print("=" * 50)
print("Follows the 5-step process you outlined")
print("=" * 50)

# For demonstration, creating sample data
np.random.seed(42)
n_days = 252  # 1 year of trading days

# Create sample stock returns with different correlations
stock_returns = pd.DataFrame({
    'NVIDIA': np.random.normal(0.0012, 0.025, n_days),
    'Google': 0.7 * np.random.normal(0.0009, 0.020, n_days) + 0.3 * np.random.normal(0.0010, 0.018, n_days),
    'Apple': 0.4 * np.random.normal(0.0008, 0.016, n_days) + np.random.normal(0.0006, 0.012, n_days),
    'Microsoft': -0.2 * np.random.normal(0.0008, 0.016, n_days) + np.random.normal(0.0005, 0.010, n_days)
})

# Your portfolio weights (replace with your actual weights)
portfolio_weights = np.array([0.35, 0.25, 0.25, 0.15])  # [NVIDIA, Google, Apple, Microsoft]

# =============================================================================
# STEP 1: CORRELATION MATRIX - How stocks move together
# =============================================================================
print("\n" + "="*50)
print("STEP 1: CORRELATION MATRIX")
print("How each stock moves with the others")
print("="*50)

correlation_matrix = stock_returns.corr()
print("Correlation Values:")
print("• 1.0 = Move exactly the same")
print("• 0.0 = Move independently")
print("• -1.0 = Move in opposite directions")
print("\nYour Stock Correlations:")
print(correlation_matrix.round(3))

# Create the heatmap visualization
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', center=0,
            square=True, linewidths=0.5, cbar_kws={"shrink": 0.8},
            fmt='.3f', vmin=-1, vmax=1)
plt.title('Stock Correlation Heatmap\n(Red=Move Together, Blue=Move Opposite, White=No Correlation)')
plt.tight_layout()
plt.show()

# =============================================================================
# STEP 2: MEASURE INDIVIDUAL RISK (Volatility)
# =============================================================================
print("\n" + "="*50)
print("STEP 2: INDIVIDUAL STOCK RISK")
print("How much each stock's price fluctuates (Volatility σ)")
print("="*50)

annual_volatilities = stock_returns.std() * np.sqrt(252)
print("Annual Volatility (Risk) for Each Stock:")
print("Higher σ = More ups and downs = More risk")
print("Lower σ = More stable = Less risk\n")

for stock, volatility in annual_volatilities.items():
    print(f"{stock}: {volatility*100:.2f}% annual volatility")

# =============================================================================
# STEP 3: RISK WITHOUT DIVERSIFICATION
# =============================================================================
print("\n" + "="*50)
print("STEP 3: RISK WITHOUT DIVERSIFICATION")
print("What your risk would be if stocks moved independently")
print("="*50)

weighted_avg_risk = np.sum(portfolio_weights * annual_volatilities)
print(f"Weighted Average Risk (no diversification): {weighted_avg_risk*100:.2f}%")
print("This assumes stocks move independently - no correlation benefits")

# =============================================================================
# STEP 4: COMPARE WITH ACTUAL PORTFOLIO RISK
# =============================================================================
print("\n" + "="*50)
print("STEP 4: ACTUAL PORTFOLIO RISK")
print("Compare theoretical vs actual risk")
print("="*50)

# Calculate actual portfolio returns and risk
portfolio_daily_returns = (stock_returns * portfolio_weights).sum(axis=1)
actual_portfolio_risk = portfolio_daily_returns.std() * np.sqrt(252)
diversification_benefit = weighted_avg_risk - actual_portfolio_risk

print(f"Theoretical Risk (no diversification): {weighted_avg_risk*100:.2f}%")
print(f"Actual Portfolio Risk (with diversification): {actual_portfolio_risk*100:.2f}%")
print(f"Diversification Benefit: {diversification_benefit*100:.2f}% risk reduction")

# =============================================================================
# STEP 5: INTERPRET THE RESULTS
# =============================================================================
print("\n" + "="*50)
print("STEP 5: INTERPRETATION")
print("What your results mean for your portfolio")
print("="*50)

# Check if diversification is working
if diversification_benefit > 0:
    benefit_percentage = (diversification_benefit / weighted_avg_risk) * 100
    print(f"✅ SUCCESS! Your portfolio benefits from diversification")
    print(f"   You've reduced risk by {benefit_percentage:.1f}%")

    if benefit_percentage > 15:
        print("   🎉 Excellent diversification benefit!")
    elif benefit_percentage > 8:
        print("   👍 Good diversification benefit")
    else:
        print("   📈 Some diversification benefit")
else:
    print("❌ No diversification benefit - stocks move too similarly")

# Analyze correlation patterns
average_correlation = correlation_matrix.values[np.triu_indices_from(correlation_matrix.values, 1)].mean()
print(f"\n📊 Average correlation between your stocks: {average_correlation:.3f}")

if average_correlation < 0.3:
    print("   ✅ Excellent: Stocks have low correlation")
elif average_correlation < 0.6:
    print("   📊 Moderate: Some correlation (typical for similar stocks)")
else:
    print("   ⚠️  High correlation: Stocks move very similarly")

# Check for highly correlated pairs
high_corr_pairs = []
for i in range(len(correlation_matrix.columns)):
    for j in range(i+1, len(correlation_matrix.columns)):
        corr_value = correlation_matrix.iloc[i, j]
        if abs(corr_value) > 0.7:
            stock1 = correlation_matrix.columns[i]
            stock2 = correlation_matrix.columns[j]
            high_corr_pairs.append((stock1, stock2, corr_value))

if high_corr_pairs:
    print(f"\n⚠️  Highly correlated stock pairs ( > 0.7 correlation):")
    for stock1, stock2, corr in high_corr_pairs:
        print(f"   {stock1} & {stock2}: {corr:.3f}")

# Final summary
print("\n" + "="*50)
print("🎯 FINAL SUMMARY")
print("="*50)
print(f"1. Correlation Analysis: {'Good' if average_correlation < 0.6 else 'Needs improvement'}")
print(f"2. Diversification Benefit: {diversification_benefit*100:.2f}% risk reduction")
print(f"3. Actual Portfolio Risk: {actual_portfolio_risk*100:.2f}%")

if diversification_benefit > 0 and average_correlation < 0.6:
    print("\n✅ CONCLUSION: Your portfolio is well-diversified!")
    print("   You're getting the risk reduction benefits of diversification")
else:
    print("\n💡 RECOMMENDATION: Consider adding less correlated assets")
    print("   Examples: Bonds, international stocks, different sectors")

print("\n" + "="*50)

# =============================================================================
# ADDITIONAL: MEASURING AND VISUALIZING PORTFOLIO GROWTH & DRAWDOWN
# =============================================================================
print("MEASURING AND VISUALIZING PORTFOLIO GROWTH & DRAWDOWN")
print("="*50)

# Calculate cumulative portfolio growth
initial_investment = 10000  # Starting with $10,000
portfolio_value = initial_investment * (1 + portfolio_daily_returns).cumprod()

# Calculate drawdown
rolling_max = portfolio_value.cummax()
drawdown = (portfolio_value - rolling_max) / rolling_max

# Calculate performance metrics
total_return = (portfolio_value.iloc[-1] / initial_investment - 1) * 100
max_drawdown = drawdown.min() * 100
recovery_days = None
for i in range(len(drawdown)):
    if drawdown.iloc[i] == 0 and i > drawdown.idxmin():
        recovery_days = i - drawdown.idxmin()
        break

# Print performance summary
print("📈 PORTFOLIO PERFORMANCE SUMMARY")
print(f"Initial Investment: ${initial_investment:,.0f}")
print(f"Final Portfolio Value: ${portfolio_value.iloc[-1]:,.2f}")
print(f"Total Return: {total_return:.2f}%")
print(f"Maximum Drawdown: {max_drawdown:.2f}%")
if recovery_days:
    print(f"Time to Recover from Worst Drawdown: {recovery_days} days")
else:
    print("Portfolio hasn't fully recovered from worst drawdown")

# Create visualization
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 10))

# Portfolio value chart
ax1.plot(portfolio_value.index, portfolio_value, linewidth=2, color='blue')
ax1.set_title('Portfolio Value Over Time', fontsize=16, fontweight='bold')
ax1.set_ylabel('Portfolio Value ($)', fontsize=12)
ax1.grid(True, alpha=0.3)
ax1.tick_params(axis='x', rotation=45)

# Add value annotations
ax1.annotate(f'Final: ${portfolio_value.iloc[-1]:,.0f}',
             xy=(portfolio_value.index[-1], portfolio_value.iloc[-1]),
             xytext=(10, 10), textcoords='offset points',
             bbox=dict(boxstyle='round,pad=0.3', facecolor='white', alpha=0.8),
             arrowprops=dict(arrowstyle='->', connectionstyle='arc3,rad=0'))

# Drawdown chart
ax2.fill_between(drawdown.index, drawdown * 100, 0, color='red', alpha=0.3)
ax2.plot(drawdown.index, drawdown * 100, color='red', linewidth=1)
ax2.set_title('Portfolio Drawdown', fontsize=16, fontweight='bold')
ax2.set_ylabel('Drawdown (%)', fontsize=12)
ax2.set_xlabel('Time', fontsize=12)
ax2.grid(True, alpha=0.3)
ax2.tick_params(axis='x', rotation=45)

# Add max drawdown annotation
max_dd_idx = drawdown.idxmin()
ax2.annotate(f'Max Drawdown: {max_drawdown:.2f}%',
             xy=(max_dd_idx, max_drawdown),
             xytext=(10, -30), textcoords='offset points',
             bbox=dict(boxstyle='round,pad=0.3', facecolor='white', alpha=0.8),
             arrowprops=dict(arrowstyle='->', connectionstyle='arc3,rad=0'))

plt.tight_layout()
plt.show()

# Calculate and display rolling volatility
rolling_volatility = portfolio_daily_returns.rolling(window=30).std() * np.sqrt(252) * 100

plt.figure(figsize=(12, 6))
plt.plot(rolling_volatility.index, rolling_volatility, color='purple', linewidth=2)
plt.title('30-Day Rolling Portfolio Volatility', fontsize=16, fontweight='bold')
plt.ylabel('Annualized Volatility (%)', fontsize=12)
plt.xlabel('Time', fontsize=12)
plt.grid(True, alpha=0.3)
plt.axhline(y=actual_portfolio_risk*100, color='red', linestyle='--',
            label=f'Overall Volatility: {actual_portfolio_risk*100:.2f}%')
plt.legend()
plt.tight_layout()
plt.show()

print("\n" + "="*50)
print("PORTFOLIO GROWTH & DRAWDOWN ANALYSIS COMPLETE")
print("="*50)

# =============================================================================
# ADDITIONAL ANALYSIS: HOW BAD CAN LOSSES GET ON REALLY BAD DAYS?
# =============================================================================
print("\n" + "="*60)
print("HOW BAD CAN LOSSES GET ON REALLY BAD DAYS?")
print("="*60)

# Calculate daily portfolio returns (already calculated as portfolio_daily_returns)
# Let's also calculate individual stock daily returns for comparison
print("Analyzing potential losses using Value at Risk (VaR) and Expected Shortfall (ES)...")

# Confidence levels for risk analysis
confidence_levels = [0.90, 0.95, 0.99]

print("\n" + "-"*50)
print("PORTFOLIO RISK ASSESSMENT")
print("-"*50)

# Calculate Value at Risk (VaR) and Expected Shortfall (ES) for portfolio
print("\nPortfolio Risk Metrics (Based on Historical Data):")
for confidence in confidence_levels:
    var = np.percentile(portfolio_daily_returns, (1-confidence)*100)
    # Expected Shortfall (average of losses beyond VaR)
    es = portfolio_daily_returns[portfolio_daily_returns <= var].mean()

    print(f"\n{confidence*100:.0f}% Confidence Level:")
    print(f"  Value at Risk (VaR): {var*100:.2f}% (Worst-case daily loss)")
    print(f"  Expected Shortfall (ES): {es*100:.2f}% (Average loss on worst days)")

# Compare with individual stocks
print("\n" + "-"*50)
print("COMPARISON WITH INDIVIDUAL STOCKS")
print("-"*50)
print("Worst Single-Day Losses (Historical):")

worst_losses = {}
for stock in stock_returns.columns:
    worst_loss = stock_returns[stock].min() * 100
    worst_losses[stock] = worst_loss
    print(f"  {stock}: {worst_loss:.2f}%")

# Portfolio's worst day
portfolio_worst_day = portfolio_daily_returns.min() * 100
print(f"  Portfolio: {portfolio_worst_day:.2f}%")

# Stress testing - correlated bad days
print("\n" + "-"*50)
print("STRESS TESTING: CORRELATED BAD DAYS")
print("-"*50)
print("Simulating scenarios where all stocks have bad days simultaneously:")

# Find the 5 worst days for the portfolio
worst_days = portfolio_daily_returns.nsmallest(5)

print("\nTop 5 Worst Days for Portfolio:")
for i, (date, loss) in enumerate(worst_days.items(), 1):
    print(f"{i}. {date.strftime('%Y-%m-%d') if hasattr(date, 'strftime') else date}: {loss*100:.2f}% loss")

    # Show how each stock performed on that day
    if hasattr(date, 'strftime'):  # If we have proper dates
        day_returns = stock_returns.loc[date]
        for stock in stock_returns.columns:
            print(f"   {stock}: {day_returns[stock]*100:+.2f}%")
    print()

# Monte Carlo simulation for potential losses
print("\n" + "-"*50)
print("MONTE CARLO SIMULATION: POTENTIAL EXTREME LOSSES")
print("-"*50)
print("Running 10,000 simulations based on historical volatility and correlations...")

# Use the covariance matrix for more accurate simulation
cov_matrix = stock_returns.cov()
n_simulations = 10000
simulated_returns = []

for _ in range(n_simulations):
    # Generate correlated random returns
    correlated_returns = np.random.multivariate_normal(
        stock_returns.mean(),
        cov_matrix
    )
    # Calculate portfolio return
    port_return = np.dot(portfolio_weights, correlated_returns)
    simulated_returns.append(port_return)

simulated_returns = np.array(simulated_returns)

# Calculate VaR and ES from simulations
print("\nMonte Carlo Simulation Results:")
for confidence in confidence_levels:
    var_sim = np.percentile(simulated_returns, (1-confidence)*100)
    es_sim = simulated_returns[simulated_returns <= var_sim].mean()

    print(f"\n{confidence*100:.0f}% Confidence Level:")
    print(f"  Simulated VaR: {var_sim*100:.2f}%")
    print(f"  Simulated ES: {es_sim*100:.2f}%")

# Worst-case scenario analysis
worst_case_sim = simulated_returns.min() * 100
print(f"\nWorst-case scenario in simulations: {worst_case_sim:.2f}% loss")

# Visualization of potential losses
plt.figure(figsize=(12, 8))

# Plot histogram of simulated returns
plt.hist(simulated_returns * 100, bins=50, alpha=0.7, color='steelblue', edgecolor='black')
plt.axvline(x=0, color='black', linestyle='--', linewidth=1)
plt.axvline(x=np.percentile(simulated_returns, 5) * 100, color='red', linestyle='--',
            linewidth=2, label='5% VaR (95% Confidence)')
plt.axvline(x=np.percentile(simulated_returns, 1) * 100, color='darkred', linestyle='--',
            linewidth=2, label='1% VaR (99% Confidence)')

plt.title('Distribution of Simulated Daily Portfolio Returns', fontsize=16, fontweight='bold')
plt.xlabel('Daily Return (%)', fontsize=12)
plt.ylabel('Frequency', fontsize=12)
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# Risk management recommendations
print("\n" + "-"*50)
print("RISK MANAGEMENT RECOMMENDATIONS")
print("-"*50)

# Calculate probability of various loss thresholds
loss_thresholds = [-1, -2, -3, -5]  # -1%, -2%, etc.
for threshold in loss_thresholds:
    prob = (simulated_returns * 100 < threshold).mean() * 100
    print(f"Probability of losing more than {abs(threshold)}% in a day: {prob:.2f}%")

# Compare portfolio risk to individual stocks
portfolio_var_95 = np.percentile(portfolio_daily_returns, 5) * 100
print(f"\nPortfolio 95% VaR: {portfolio_var_95:.2f}%")
print("Individual Stock 95% VaR:")
for stock in stock_returns.columns:
    stock_var = np.percentile(stock_returns[stock], 5) * 100
    print(f"  {stock}: {stock_var:.2f}%")

# Final assessment
max_daily_loss = min(portfolio_worst_day, worst_case_sim)
if max_daily_loss > -8:
    risk_level = "Moderate"
    recommendation = "Your portfolio appears to have reasonable risk controls. Consider maintaining your current diversification strategy."
elif max_daily_loss > -15:
    risk_level = "High"
    recommendation = "Your portfolio could experience significant losses on bad days. Consider reducing exposure to high-volatility assets."
else:
    risk_level = "Very High"
    recommendation = "Your portfolio is vulnerable to extreme losses. Consider implementing hedging strategies or reducing risk exposure."

print(f"\nOverall Risk Assessment: {risk_level}")
print(f"Recommendation: {recommendation}")

print("\n" + "="*60)
print("LOSS ANALYSIS COMPLETE")
print("="*60)

# =============================================================================
# BACKTESTING YOUR VAR MODEL
# =============================================================================
print("\n" + "="*60)
print("BACKTESTING YOUR VAR MODEL – DOES IT REALLY WORK?")
print("="*60)

print("Backtesting compares predicted risk (VaR) with actual portfolio performance")
print("to validate if your risk model is accurate.\n")

# Calculate VaR at 95% confidence level
var_95 = np.percentile(portfolio_daily_returns, 5)
print(f"Your 95% VaR estimate: {var_95*100:.2f}% daily loss")

# Count how many times the actual loss exceeded VaR
exceptions = portfolio_daily_returns < var_95
num_exceptions = exceptions.sum()
total_days = len(portfolio_daily_returns)
exception_rate = num_exceptions / total_days

print(f"\nBacktest Results:")
print(f"Total trading days: {total_days}")
print(f"Days where loss exceeded VaR: {num_exceptions}")
print(f"Exception rate: {exception_rate*100:.2f}% (should be close to 5%)")

# Statistical test for VaR accuracy
expected_exceptions = total_days * 0.05
unexpected_exceptions = abs(num_exceptions - expected_exceptions)

print(f"\nStatistical Validation:")
print(f"Expected exceptions (5% of days): {expected_exceptions:.1f}")
print(f"Actual exceptions: {num_exceptions}")

if unexpected_exceptions <= 2:
    print("✅ VaR model validation: PASS - Exception rate is within acceptable range")
elif unexpected_exceptions <= 5:
    print("⚠️  VaR model validation: CAUTION - Exception rate is slightly outside expected range")
else:
    print("❌ VaR model validation: FAIL - Exception rate is significantly different from expected")

# Analyze the magnitude of exceptions
if num_exceptions > 0:
    exception_losses = portfolio_daily_returns[exceptions]
    avg_exception_loss = exception_losses.mean() * 100
    max_exception_loss = exception_losses.min() * 100

    print(f"\nAnalysis of VaR Breaches:")
    print(f"Average loss on exception days: {avg_exception_loss:.2f}%")
    print(f"Maximum loss on exception days: {max_exception_loss:.2f}%")

    # Compare with Expected Shortfall
    es_95 = exception_losses.mean()
    print(f"Actual average loss beyond VaR: {es_95*100:.2f}%")
    print(f"Your ES estimate was: {np.percentile(simulated_returns, 5)*100:.2f}%")

# Visualize the backtesting results
plt.figure(figsize=(14, 10))

# Plot 1: Daily returns with VaR threshold
plt.subplot(2, 1, 1)
plt.plot(portfolio_daily_returns.index, portfolio_daily_returns * 100,
         color='blue', alpha=0.7, linewidth=1, label='Daily Returns')
plt.axhline(y=var_95*100, color='red', linestyle='--',
            linewidth=2, label='95% VaR Threshold')
plt.fill_between(portfolio_daily_returns.index,
                 var_95*100, portfolio_daily_returns.min()*100,
                 color='red', alpha=0.2, label='VaR Breach Zone')

# Highlight exceptions
exception_dates = portfolio_daily_returns.index[exceptions]
exception_returns = portfolio_daily_returns[exceptions] * 100
plt.scatter(exception_dates, exception_returns,
            color='red', s=30, zorder=5, label='VaR Exceptions')

plt.title('Backtesting VaR Model: Daily Returns vs. VaR Threshold', fontsize=16, fontweight='bold')
plt.ylabel('Daily Return (%)', fontsize=12)
plt.legend()
plt.grid(True, alpha=0.3)

# Plot 2: Cumulative exceptions count
plt.subplot(2, 1, 2)
cumulative_exceptions = exceptions.cumsum()
expected_cumulative = np.arange(1, total_days+1) * 0.05

plt.plot(portfolio_daily_returns.index, cumulative_exceptions,
         color='red', linewidth=2, label='Actual Exceptions')
plt.plot(portfolio_daily_returns.index, expected_cumulative,
         color='green', linestyle='--', linewidth=2, label='Expected Exceptions (5%)')

# Add confidence intervals for expected exceptions
upper_ci = expected_cumulative + 1.96 * np.sqrt(expected_cumulative * 0.95)
lower_ci = np.maximum(0, expected_cumulative - 1.96 * np.sqrt(expected_cumulative * 0.95))

plt.fill_between(portfolio_daily_returns.index, lower_ci, upper_ci,
                 color='green', alpha=0.2, label='95% Confidence Interval')

plt.title('Cumulative VaR Exceptions Over Time', fontsize=16, fontweight='bold')
plt.ylabel('Cumulative Exceptions', fontsize=12)
plt.xlabel('Time', fontsize=12)
plt.legend()
plt.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

# Conditional Coverage Test (Christoffersen test)
print("\n" + "-"*50)
print("ADVANCED BACKTESTING: CONDITIONAL COVERAGE TEST")
print("-"*50)

# Check for clustering of exceptions
if num_exceptions > 1:
    exception_indices = np.where(exceptions)[0]
    exception_gaps = np.diff(exception_indices)

    clustered_exceptions = any(exception_gaps == 1)  # Consecutive days

    if clustered_exceptions:
        print("❌ Potential clustering of exceptions detected")
        print("   This suggests your VaR model may not capture time-varying volatility")
    else:
        print("✅ No clustering of exceptions - good model performance")

    # Calculate average gap between exceptions
    avg_gap = exception_gaps.mean() if len(exception_gaps) > 0 else float('inf')
    print(f"   Average days between exceptions: {avg_gap:.1f}")
else:
    print("Insufficient exceptions for clustering analysis")

# Stress test the VaR model with historical crises
print("\n" + "-"*50)
print("STRESS TEST: HOW WOULD YOUR VaR MODEL PERFORM IN A CRISIS?")
print("-"*50)

# Simulate a crisis period (e.g., COVID-19 crash pattern)
crisis_volatility_multiplier = 2.5  # Volatility increases during crises
crisis_correlation_increase = 0.3   # Correlations increase during crises

# Create a crisis covariance matrix
crisis_cov_matrix = cov_matrix * crisis_volatility_multiplier
# Increase correlations
crisis_corr_matrix = correlation_matrix.copy()
np.fill_diagonal(crisis_corr_matrix.values, 1)
crisis_corr_matrix = crisis_corr_matrix + crisis_correlation_increase
crisis_corr_matrix = np.clip(crisis_corr_matrix, -1, 1)

# Convert back to covariance matrix
crisis_volatilities = np.sqrt(np.diag(crisis_cov_matrix))
crisis_cov_matrix = np.diag(crisis_volatilities) @ crisis_corr_matrix @ np.diag(crisis_volatilities)

# Simulate crisis returns
crisis_returns = []
for _ in range(1000):  # Simulate 1000 crisis days
    correlated_returns = np.random.multivariate_normal(
        stock_returns.mean() * 0.8,  # Lower returns during crisis
        crisis_cov_matrix
    )
    port_return = np.dot(portfolio_weights, correlated_returns)
    crisis_returns.append(port_return)

crisis_returns = np.array(crisis_returns)

# Calculate crisis VaR and compare to normal VaR
crisis_var_95 = np.percentile(crisis_returns, 5)
crisis_es_95 = crisis_returns[crisis_returns <= crisis_var_95].mean()

print(f"Normal conditions 95% VaR: {var_95*100:.2f}%")
print(f"Crisis conditions 95% VaR: {crisis_var_95*100:.2f}%")
print(f"Increase in risk during crisis: {(crisis_var_95/var_95 - 1)*100:.1f}%")

print(f"\nNormal conditions 95% ES: {es_95*100:.2f}%")
print(f"Crisis conditions 95% ES: {crisis_es_95*100:.2f}%")
print(f"Increase in tail risk during crisis: {(crisis_es_95/es_95 - 1)*100:.1f}%")

# Final assessment of VaR model
print("\n" + "-"*50)
print("FINAL VaR MODEL ASSESSMENT")
print("-"*50)

if unexpected_exceptions <= 2 and not clustered_exceptions:
    print("✅ STRONG VALIDATION: Your VaR model appears accurate and reliable")
    print("   It correctly predicts risk levels in most market conditions")
elif unexpected_exceptions <= 5:
    print("⚠️  ACCEPTABLE VALIDATION: Your VaR model is reasonable but could be improved")
    print("   Consider refining your model or using a higher confidence level")
else:
    print("❌ POOR VALIDATION: Your VaR model significantly underestimates risk")
    print("   You should:")
    print("   1. Use a more conservative confidence level (e.g., 99%)")
    print("   2. Incorporate fat-tailed distributions in your model")
    print("   3. Implement additional stress testing")

print(f"\nRecommendation for risk management:")
if crisis_var_95 < var_95 * 1.5:
    print("✅ Your portfolio shows reasonable resilience to crisis conditions")
else:
    print("⚠️  Your portfolio may be vulnerable to significant losses in crisis conditions")
    print("   Consider adding hedging strategies or safe-haven assets")

print("\n" + "="*60)
print("VAR BACKTESTING COMPLETE")
print("="*60)

# =============================================================================
# ROLLING HISTORICAL VAR – HOW RISK CHANGES OVER TIME
# =============================================================================
print("\n" + "="*60)
print("ROLLING HISTORICAL VAR – HOW RISK CHANGES OVER TIME")
print("="*60)

print("Analyzing how your portfolio risk evolves using rolling windows...")
print("This shows how VaR changes during different market regimes.\n")

# Make sure index is datetime
portfolio_daily_returns.index = pd.to_datetime(portfolio_daily_returns.index)

# Set rolling window parameters (3-month and 6-month windows)
window_sizes = [63, 126]  # Approximately 3 months and 6 months in trading days

# Calculate rolling VaR for different confidence levels
confidence_levels = [0.90, 0.95, 0.99]

# Create figure for visualization
plt.figure(figsize=(14, 10))

for i, confidence in enumerate(confidence_levels, 1):
    plt.subplot(3, 1, i)

    # Calculate VaR for each window size
    for window in window_sizes:
        # Calculate rolling VaR
        rolling_var = portfolio_daily_returns.rolling(window=window).quantile(1 - confidence)

        # Plot the rolling VaR
        plt.plot(rolling_var.index, rolling_var * 100,
                label=f'{window}-day window ({confidence*100:.0f}% VaR)',
                linewidth=1.5)

    # Add actual returns for context
    plt.plot(portfolio_daily_returns.index, portfolio_daily_returns * 100,
            color='gray', alpha=0.4, linewidth=0.8, label='Daily Returns')

    plt.title(f'Rolling {confidence*100:.0f}% Value at Risk', fontsize=14, fontweight='bold')
    plt.ylabel('VaR (%)', fontsize=12)
    plt.legend()
    plt.grid(True, alpha=0.3)

    # Add shaded areas for high risk periods
    high_risk_periods = rolling_var[rolling_var < rolling_var.quantile(0.25)]  # Bottom 25% = highest risk
    for period in high_risk_periods.dropna().index:
        plt.axvspan(period, period, alpha=0.2, color='red')

plt.xlabel('Time', fontsize=12)
plt.tight_layout()
plt.show()

# Analyze how VaR changes over time
print("\n" + "-"*50)
print("ANALYSIS OF RISK REGIME CHANGES")
print("-"*50)

# Calculate statistics for 6-month rolling 95% VaR
rolling_var_95 = portfolio_daily_returns.rolling(window=126).quantile(0.05)
rolling_var_95_pct = rolling_var_95 * 100

print(f"6-month Rolling 95% VaR Statistics:")
print(f"Average VaR: {rolling_var_95_pct.mean():.2f}%")
print(f"Minimum VaR: {rolling_var_95_pct.min():.2f}% (lowest risk period)")
print(f"Maximum VaR: {rolling_var_95_pct.max():.2f}% (highest risk period)")
print(f"Range: {rolling_var_95_pct.max() - rolling_var_95_pct.min():.2f}%")

# Identify high and low risk periods
high_risk_threshold = rolling_var_95_pct.quantile(0.75)  # Top 25% = highest risk
low_risk_threshold = rolling_var_95_pct.quantile(0.25)   # Bottom 25% = lowest risk

high_risk_periods = rolling_var_95_pct[rolling_var_95_pct >= high_risk_threshold]
low_risk_periods = rolling_var_95_pct[rolling_var_95_pct <= low_risk_threshold]

print(f"\nHigh risk threshold: {high_risk_threshold:.2f}%")
print(f"Low risk threshold: {low_risk_threshold:.2f}%")

print(f"\nNumber of high risk periods: {len(high_risk_periods)}")
print(f"Number of low risk periods: {len(low_risk_periods)}")

# =============================================================================
# PERFORMANCE AFTER HIGH RISK PERIODS (Corrected Section)
# =============================================================================
print("\n" + "-"*50)
print("PERFORMANCE AFTER HIGH RISK PERIODS")
print("-"*50)

forward_returns = []

# Loop through high risk periods
for date in high_risk_periods.index:
    try:
        # Look 21 trading days (~1 month) ahead
        future_date = date + pd.Timedelta(days=21)

        # If we actually have data for that date (or nearest available)
        if future_date in portfolio_daily_returns.index:
            future_return = portfolio_daily_returns.loc[date:future_date].sum() * 100
            forward_returns.append(future_return)
        else:
            # Use nearest available ~21 days later
            valid_dates = portfolio_daily_returns.loc[date:].index
            if len(valid_dates) > 21:
                future_return = portfolio_daily_returns.loc[date:valid_dates[21]].sum() * 100
                forward_returns.append(future_return)
    except Exception as e:
        print(f"⚠️ Skipped {date}: {e}")

# Summary
if forward_returns:
    avg_forward_return = np.mean(forward_returns)
    print(f"Average return 1 month after high risk periods: {avg_forward_return:.2f}%")

    if avg_forward_return > 0:
        print("✅ High risk periods often followed by positive returns (mean reversion)")
    else:
        print("⚠️ High risk periods tend to persist (momentum effect)")
else:
    print("No forward returns could be calculated.")

# Compare with static VaR
static_var_95 = np.percentile(portfolio_daily_returns, 0.05) * 100
print(f"\nStatic 95% VaR (full period): {static_var_95:.2f}%")
print(f"Rolling 95% VaR range: {rolling_var_95_pct.min():.2f}% to {rolling_var_95_pct.max():.2f}%")

if static_var_95 < rolling_var_95_pct.mean():
    print("✅ Static VaR is conservative compared to average rolling VaR")
elif static_var_95 > rolling_var_95_pct.mean():
    print("⚠️  Static VaR may underestimate risk compared to average rolling VaR")
else:
    print("📊 Static VaR is consistent with average rolling VaR")

# Risk regime detection
print("\n" + "-"*50)
print("RISK REGIME DETECTION")
print("-"*50)

# Use change point detection to identify shifts in risk regimes
from scipy import stats

# Calculate rolling volatility as proxy for risk
rolling_volatility = portfolio_daily_returns.rolling(window=63).std() * np.sqrt(252) * 100

# Simple regime detection based on volatility
high_vol_regime = rolling_volatility > rolling_volatility.quantile(0.75)
low_vol_regime = rolling_volatility < rolling_volatility.quantile(0.25)

print(f"High volatility regime days: {high_vol_regime.sum()}")
print(f"Low volatility regime days: {low_vol_regime.sum()}")

# Compare performance in different regimes
high_vol_returns = portfolio_daily_returns[high_vol_regime].mean() * 252 * 100
low_vol_returns = portfolio_daily_returns[low_vol_regime].mean() * 252 * 100

print(f"\nAnnualized returns in high volatility periods: {high_vol_returns:.2f}%")
print(f"Annualized returns in low volatility periods: {low_vol_returns:.2f}%")

# Calculate risk-adjusted returns in different regimes
high_vol_sharpe = high_vol_returns / rolling_volatility[high_vol_regime].mean() if rolling_volatility[high_vol_regime].mean() > 0 else 0
low_vol_sharpe = low_vol_returns / rolling_volatility[low_vol_regime].mean() if rolling_volatility[low_vol_regime].mean() > 0 else 0

print(f"\nRisk-adjusted returns (Sharpe) in high volatility periods: {high_vol_sharpe:.2f}")
print(f"Risk-adjusted returns (Sharpe) in low volatility periods: {low_vol_sharpe:.2f}")

# Visualize risk regimes
plt.figure(figsize=(14, 8))

# Plot rolling volatility
plt.plot(rolling_volatility.index, rolling_volatility, color='purple', linewidth=2, label='Rolling Volatility')

# Highlight high and low volatility regimes
plt.fill_between(rolling_volatility.index,
                 rolling_volatility,
                 where=high_vol_regime,
                 color='red', alpha=0.3, label='High Volatility Regime')
plt.fill_between(rolling_volatility.index,
                 rolling_volatility,
                 where=low_vol_regime,
                 color='green', alpha=0.3, label='Low Volatility Regime')

plt.axhline(y=rolling_volatility.quantile(0.75), color='red', linestyle='--', alpha=0.7, label='75th Percentile')
plt.axhline(y=rolling_volatility.quantile(0.25), color='green', linestyle='--', alpha=0.7, label='25th Percentile')

plt.title('Risk Regime Detection Based on Rolling Volatility', fontsize=16, fontweight='bold')
plt.ylabel('Annualized Volatility (%)', fontsize=12)
plt.xlabel('Time', fontsize=12)
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# Recommendations based on rolling VaR analysis
print("\n" + "-"*50)
print("PORTFOLIO RISK MANAGEMENT RECOMMENDATIONS")
print("-"*50)

if rolling_var_95_pct.max() - rolling_var_95_pct.min() > 5:
    print("⚠️  Your portfolio experiences significant risk regime changes")
    print("   Consider dynamic risk management strategies")
else:
    print("✅ Your portfolio risk is relatively stable across time")

if high_vol_sharpe < low_vol_sharpe:
    print("📉 Your portfolio performs poorly during high volatility periods")
    print("   Consider adding defensive assets or hedging strategies")
else:
    print("📈 Your portfolio handles high volatility environments well")

print(f"\nAverage rolling VaR: {rolling_var_95_pct.mean():.2f}%")
if len(rolling_var_95_pct) > 0:
    print(f"Current VaR estimate: {rolling_var_95_pct.iloc[-1]:.2f}%")
    if rolling_var_95_pct.iloc[-1] > rolling_var_95_pct.mean():
        print("🚨 Current risk level is above historical average")
    else:
        print("✅ Current risk level is at or below historical average")

print("\n" + "="*60)
print("ROLLING VAR ANALYSIS COMPLETE")
print("="*60)

# =============================================================================
# TESTING IF YOUR RETURNS FOLLOW A NORMAL DISTRIBUTION (JARQUE-BERA TEST)
# =============================================================================
print("\n" + "="*70)
print("TESTING IF YOUR RETURNS FOLLOW A NORMAL DISTRIBUTION")
print("="*70)

print("Using the Jarque-Bera test to check if portfolio returns are normally distributed...")
print("This is important because many risk models assume normality.\n")

# Import necessary statistical functions
from scipy import stats

# =============================================================================
# STEP 1: Calculate descriptive statistics
# =============================================================================
print("-"*50)
print("STEP 1: DESCRIPTIVE STATISTICS")
print("-"*50)

returns = portfolio_daily_returns
mean_return = returns.mean() * 100
std_return = returns.std() * 100
skewness = stats.skew(returns)
kurtosis = stats.kurtosis(returns)  # Excess kurtosis (normal dist = 0)

print(f"Mean daily return: {mean_return:.4f}%")
print(f"Standard deviation: {std_return:.4f}%")
print(f"Skewness: {skewness:.4f}")
print(f"Excess Kurtosis: {kurtosis:.4f}")

# Interpret skewness
if abs(skewness) < 0.5:
    skew_interpretation = "approximately symmetric"
elif skewness > 0.5:
    skew_interpretation = "right-skewed (more large gains)"
else:
    skew_interpretation = "left-skewed (more large losses)"

# Interpret kurtosis
if abs(kurtosis) < 1:
    kurt_interpretation = "approximately normal tails"
elif kurtosis > 1:
    kurt_interpretation = "fat-tailed (more extreme events than normal)"
else:
    kurt_interpretation = "thin-tailed (fewer extreme events than normal)"

print(f"\nInterpretation:")
print(f"- Distribution is {skew_interpretation}")
print(f"- Distribution has {kurt_interpretation}")

# =============================================================================
# STEP 2: Perform Jarque-Bera test
# =============================================================================
print("\n" + "-"*50)
print("STEP 2: JARQUE-BERA TEST")
print("-"*50)

# Perform the Jarque-Bera test
jb_stat, jb_pvalue = stats.jarque_bera(returns)

print(f"Jarque-Bera test statistic: {jb_stat:.4f}")
print(f"P-value: {jb_pvalue:.6f}")

# Interpret the results
alpha = 0.05  # Significance level
if jb_pvalue < alpha:
    print("✅ REJECT the null hypothesis")
    print("   Your returns are NOT normally distributed")
else:
    print("❌ FAIL TO REJECT the null hypothesis")
    print("   Your returns MAY be normally distributed")

print(f"\nThe test checks if skewness ≈ 0 and kurtosis ≈ 3 (excess kurtosis ≈ 0)")

# =============================================================================
# STEP 3: Compare with normal distribution
# =============================================================================
print("\n" + "-"*50)
print("STEP 3: COMPARISON WITH NORMAL DISTRIBUTION")
print("-"*50)

# Generate a normal distribution with same mean and std
normal_data = np.random.normal(returns.mean(), returns.std(), len(returns))

# Compare statistics
normal_skewness = stats.skew(normal_data)
normal_kurtosis = stats.kurtosis(normal_data)

print("Comparison with normal distribution:")
print(f"               Actual   Normal")
print(f"Skewness:      {skewness:8.4f}  {normal_skewness:8.4f}")
print(f"Excess Kurtosis: {kurtosis:8.4f}  {normal_kurtosis:8.4f}")

# Calculate how many standard deviations away from normal
skew_deviation = abs(skewness - normal_skewness) / abs(normal_skewness) if normal_skewness != 0 else float('inf')
kurt_deviation = abs(kurtosis - normal_kurtosis) / abs(normal_kurtosis) if normal_kurtosis != 0 else float('inf')

print(f"\nDeviation from normal:")
print(f"Skewness: {skew_deviation*100:.1f}% different from normal")
print(f"Kurtosis: {kurt_deviation*100:.1f}% different from normal")

# =============================================================================
# STEP 4: Visual comparison
# =============================================================================
print("\n" + "-"*50)
print("STEP 4: VISUAL COMPARISON")
print("-"*50)

# Create visualizations
fig, axes = plt.subplots(2, 2, figsize=(15, 12))

# Plot 1: Histogram with normal curve
axes[0, 0].hist(returns, bins=50, density=True, alpha=0.7, color='steelblue', edgecolor='black')
x = np.linspace(returns.min(), returns.max(), 100)
axes[0, 0].plot(x, stats.norm.pdf(x, returns.mean(), returns.std()), 'r-', lw=2, label='Normal Distribution')
axes[0, 0].set_title('Histogram of Returns vs. Normal Distribution', fontweight='bold')
axes[0, 0].set_xlabel('Daily Return')
axes[0, 0].set_ylabel('Density')
axes[0, 0].legend()
axes[0, 0].grid(True, alpha=0.3)

# Plot 2: Q-Q Plot
stats.probplot(returns, dist="norm", plot=axes[0, 1])
axes[0, 1].set_title('Q-Q Plot: Returns vs. Normal Distribution', fontweight='bold')
axes[0, 1].grid(True, alpha=0.3)

# Plot 3: Box plot comparing actual vs normal
boxplot_data = [returns, normal_data]
axes[1, 0].boxplot(boxplot_data, labels=['Actual Returns', 'Normal Data'])
axes[1, 0].set_title('Box Plot Comparison', fontweight='bold')
axes[1, 0].set_ylabel('Daily Return')
axes[1, 0].grid(True, alpha=0.3)

# Plot 4: Cumulative distribution function
sorted_returns = np.sort(returns)
cdf_actual = np.arange(1, len(sorted_returns)+1) / len(sorted_returns)
cdf_normal = stats.norm.cdf(sorted_returns, returns.mean(), returns.std())

axes[1, 1].plot(sorted_returns, cdf_actual, label='Actual Returns', linewidth=2)
axes[1, 1].plot(sorted_returns, cdf_normal, label='Normal Distribution', linewidth=2)
axes[1, 1].set_title('Cumulative Distribution Function Comparison', fontweight='bold')
axes[1, 1].set_xlabel('Daily Return')
axes[1, 1].set_ylabel('Cumulative Probability')
axes[1, 1].legend()
axes[1, 1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

# =============================================================================
# STEP 5: Implications for risk management
# =============================================================================
print("\n" + "-"*50)
print("STEP 5: IMPLICATIONS FOR RISK MANAGEMENT")
print("-"*50)

print("Why normality matters for risk management:")
print("- VaR models often assume normal distribution")
print("- Non-normal returns can lead to underestimating risk")
print("- Fat tails mean extreme events happen more often than models predict")

if jb_pvalue < alpha:
    print(f"\n🚨 YOUR RETURNS ARE NOT NORMAL - RISK IMPLICATIONS:")

    if kurtosis > 1:
        print("• Fat tails detected: Extreme losses occur more frequently than normal distribution predicts")
        print("• Your VaR likely UNDERESTIMATES true risk")
        print("• Consider using Expected Shortfall or extreme value theory")

    if skewness < -0.5:
        print("• Negative skewness detected: More large losses than large gains")
        print("• Downside risk is higher than symmetric models assume")

    if skewness > 0.5:
        print("• Positive skewness detected: More large gains than large losses")
        print("• Potential for better upside than normal distribution suggests")

    print(f"\n💡 RECOMMENDATIONS:")
    print("• Use historical simulation instead of parametric VaR")
    print("• Consider Student's t-distribution or other fat-tailed distributions")
    print("• Implement stress testing for extreme events")
    print("• Use Expected Shortfall instead of VaR for tail risk measurement")

else:
    print(f"\n✅ YOUR RETURNS APPEAR NORMAL - RISK IMPLICATIONS:")
    print("• Parametric VaR models should work reasonably well")
    print("• Normal distribution assumptions are approximately valid")
    print("• Standard risk models should provide accurate estimates")

# =============================================================================
# STEP 6: Test individual assets
# =============================================================================
print("\n" + "-"*50)
print("STEP 6: NORMALITY TEST FOR INDIVIDUAL ASSETS")
print("-"*50)

print("Checking if individual stocks follow normal distribution:\n")

non_normal_assets = []
for stock in stock_returns.columns:
    stock_returns_data = stock_returns[stock].dropna()
    jb_stat_stock, jb_pvalue_stock = stats.jarque_bera(stock_returns_data)
    skewness_stock = stats.skew(stock_returns_data)
    kurtosis_stock = stats.kurtosis(stock_returns_data)

    normal = jb_pvalue_stock >= 0.05
    status = "NORMAL" if normal else "NON-NORMAL"

    print(f"{stock:12} | {status:11} | p-value: {jb_pvalue_stock:.4f} | Skew: {skewness_stock:.2f} | Kurtosis: {kurtosis_stock:.2f}")

    if not normal:
        non_normal_assets.append(stock)

if non_normal_assets:
    print(f"\nNon-normal assets: {', '.join(non_normal_assets)}")
    print("These assets contribute to non-normality in your portfolio")
else:
    print(f"\nAll individual assets appear normally distributed")

# =============================================================================
# FINAL ASSESSMENT
# =============================================================================
print("\n" + "="*70)
print("FINAL ASSESSMENT: NORMALITY OF RETURNS")
print("="*70)

if jb_pvalue < alpha:
    print("❌ CONCLUSION: Your portfolio returns DO NOT follow a normal distribution")
    print("   This is TYPICAL for financial returns - most exhibit fat tails and skewness")
else:
    print("✅ CONCLUSION: Your portfolio returns appear to follow a normal distribution")
    print("   This is UNUSUAL for financial returns - most exhibit some non-normality")

print(f"\nKey characteristics:")
print(f"• Skewness: {skewness:.4f} ({skew_interpretation})")
print(f"• Excess Kurtosis: {kurtosis:.4f} ({kurt_interpretation})")
print(f"• Jarque-Bera p-value: {jb_pvalue:.6f}")

print(f"\nRisk management implications:")
if kurtosis > 1:
    print("• Extreme events will occur more frequently than normal models predict")
    print("• You should add a safety margin to your VaR estimates")
if skewness < -0.5:
    print("• Large losses are more common than large gains")
    print("• Focus on downside risk protection")

print("\n" + "="*70)
print("NORMALITY TESTING COMPLETE")
print("="*70)

